# Pipeline: Deploy Onboarded Service
# Uses the onboarded_service (Kubernetes). Rolling deployment to k8sdev / eks.
pipeline:
  name: Deploy Onboarded Service
  identifier: deploy_onboarded_service
  projectIdentifier: PM_Signoff
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: deploy
        description: Rolling deploy for Onboarded Service
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: onboarded_service
          environment:
            environmentRef: k8sdev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: eks
          execution:
            steps:
              - step:
                  name: Rolling Deploy
                  identifier: rolling_deploy
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Rolling Rollback
                  identifier: rolling_rollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
